### PR TITLE
Update db.json

### PR DESCRIPTION
**Pull request by mortdudley**

### CODE REVIEW

**Comment by jrgrimshaw** [comment]
Hey thanks for the PR @mortdudley 
Do you have any proof for this being caused by the artifact 10309 specifically?

**Comment by mortdudley** [comment]
Hey @jrgrimshaw ,

The issue didn’t exist prior to updating today to 10309 then down to 10300. The issue exists on both of those builds but disappeared when we downgraded back to 10072. 

I can’t be sure if the problem exists on any of the builds between 10072 and 10300.

**Comment by mortdudley** [comment]
This is a screenshot of the only server console error that arises when a player hits E to put their cars away

**Comment by mortdudley** [comment]
Just an update, the problem also exists for us on build 10272

**Comment by jrgrimshaw** [comment]
@mortdudley thanks for the info. I haven't tested any of these artifacts yet but one I have I'll update you :)

We are starting to get some more reports of it now so thanks for already letting us know!

**Comment by sableeyed** [comment]
10272 is also producing this issue on Windows Server (granted we may not be on the latest garages)

**Comment by mortdudley** [comment]
I should have clarified we are also on Windows Server

**Comment by jrgrimshaw** [comment]
@mortdudley @sableeyed Thanks all - I've now added all releases between `10268-10309` :)

**Pull request closed without merging**
