### PR TITLE
Update db.json

### PR DESCRIPTION
**Pull request by TylerPlayz424**

### CODE REVIEW

**Comment by jrgrimshaw** [comment]
@TylerPlayz424 Thanks so much for the PR! There were 4 artifact version releases that day, is 10271 safe or did you have to downgrade to an earlier version than that? 

Do you also have any evidence that the crashing is caused by that artifact?

**Comment by TylerPlayz424** [comment]
I had to downgrade as that was the latest available when I tried it, and there's multiple top servers in the txAdmin discord reporting the same thing.image I've attached one of them.

**Comment by jrgrimshaw** [comment]
@TylerPlayz424 Appreciate the info 🙏

**Comment by sableeyed** [comment]
This was in the txAdmin discord. If the extra crashing is the only reported problem with 10272, they may not have had the config set in their server.cfg

image

**Comment by jrgrimshaw** [comment]
@TylerPlayz424 I've now added all releases between `10268-10309` :)

**Pull request closed without merging**
